import type { Metadata } from "next"
import Image from "next/image"
import { Counter } from "@/components/motion/counter"
import { Reveal } from "@/components/motion/reveal"
import { Container } from "@/components/layout/container"
import { Section } from "@/components/layout/section"
import { FinalCta } from "@/components/sections/shared/final-cta"
import { PageHero } from "@/components/sections/shared/page-hero"
import { SectionHeader } from "@/components/ui/section-header"

export const metadata: Metadata = { title: "About", description: "Northline is an independent systems studio making AI useful inside real operations." }

const values = [{ n: "01", title: "Clarity over novelty", text: "We choose the simplest capable system and make every important decision understandable." }, { n: "02", title: "Useful before impressive", text: "A working improvement in the daily operation matters more than a polished demonstration." }, { n: "03", title: "Judgment stays human", text: "We automate repetition and coordination while preserving people’s authority over consequential decisions." }, { n: "04", title: "Built to keep changing", text: "Operations evolve. We design modular, observable systems that can evolve with them." }]

export default function AboutPage() { return <><PageHero eyebrow="About Northline" title="SMALL TEAM. SERIOUS SYSTEMS." intro="We are an independent AI systems studio combining operational thinking, product design, and technical implementation in one senior team." /><Section><Container><div className="grid gap-16 lg:grid-cols-2"><div className="relative aspect-[4/5] overflow-hidden"><Image src="/images/robotic-system.png" alt="Precision robotic system in a minimal industrial space" fill priority sizes="50vw" className="cinematic-image object-cover" /></div><div className="flex flex-col justify-center"><p className="eyebrow text-white/35">/ Our approach</p><h2 className="mt-9 text-4xl leading-[1.04] tracking-[-.045em] md:text-6xl">We make technology quieter—and the operation more capable.</h2><p className="mt-9 max-w-xl text-base leading-8 text-white/55">Northline was formed around a simple belief: intelligent systems should reduce cognitive load, not add another layer of complexity. We work close to the people doing the work, understand the decisions underneath it, and build the smallest system capable of changing the outcome.</p><p className="mt-6 max-w-xl text-base leading-8 text-white/55">Our model stays deliberately compact. The people diagnosing the constraint are the same people designing and shipping the solution.</p></div></div></Container></Section><section className="border-y border-white/10 py-14"><Container className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{[{v:12,s:"+",l:"years in systems"},{v:100,s:"+",l:"workflows shipped"},{v:9,s:"",l:"countries served"},{v:92,s:"%",l:"team adoption"}].map(stat => <div key={stat.l}><p className="text-5xl tracking-[-.05em]"><Counter value={stat.v} suffix={stat.s} /></p><p className="eyebrow mt-4 text-white/35">{stat.l}</p></div>)}</Container></section><Section><Container><SectionHeader eyebrow="What guides us" title="Principles that survive the technology cycle." /><div className="mt-20 grid md:grid-cols-2">{values.map(value => <Reveal key={value.n} className="border-t border-white/10 py-9 md:px-8 md:first:pl-0 md:[&:nth-child(2n)]:border-l"><p className="eyebrow text-white/30">/ {value.n}</p><h3 className="mt-8 text-3xl tracking-[-.04em]">{value.title}</h3><p className="mt-5 max-w-md text-sm leading-7 text-white/50">{value.text}</p></Reveal>)}</div></Container></Section><Section className="bg-[#f0f0ec] text-black"><Container><blockquote className="max-w-6xl text-4xl leading-[1.08] tracking-[-.045em] md:text-7xl">“The goal is not more automation. It is more space for judgment, craft, and useful human attention.”</blockquote><p className="eyebrow mt-10 text-black/45">/ The Northline principle</p></Container></Section><FinalCta /></> }
